### ISSUE TITLE
"Test/Mock" ability of the Configuration package

### ISSUE THREAD

**Issue by kalarani** [njupiter/njupiter#10]
Hi,

Am using the nJupiter.Configuration package and would like to know how to mock the configuration for testing in other classes. Any pointers or suggestions?

Thanks,
Kala

**Comment by twilek** [comment]
All essential classes in nJupiter.Configuration are propagated as interfaces so they shall hopefully be pretty easy to mock.

My suggestion is that you register the IConfigRepository in your IoC container and then inject it to the class where you want to use it, like in this pseudo code:

    public class MyClass {
        private readonly string myValue;

        public MyClass(IConfigRepository configRepository) {
            var config = configRepository.GetConfig(typeof(MyClass).Assembly);
            myValue = config.GetValue("myValue");
        }

        public string MyValue { get { return myValue; } }

    }
    
Then you can mock it like this (this pseudo code using FakeItEasy syntax for mocking):

    [SetUp]
    public void Setup() {
        configRepository = A.Fake<IConfigRepository>();
        config = A.Fake<IConfig>();
        A.CallTo(() => configRepository.GetConfig(typeof(MyClass).Assembly)).Returns(config);
    }
    
    [Test]
    public void Topic_ConfigContainsValue_ReturnsValueFromConfig() {
        A.CallTo(() => config.GetValue("myValue")).Returns("anyValue");
        
        var myClass = new MyClass(configRepository);

        Assert.AreEqual("anyValue", myClass.MyValue);
    }   

Another possibility would be to implement typed configs (in the same way as typed loggers in nJupiter.Abstraction.Logging, read more here: https://github.com/njupiter/njupiter/wiki/nJupiter.Abstraction.Logging#using-together-with-an-ioc-container) so you can inject a typed version of IConfig directly into your class and skip the step with the config repository. nJupiter.Configuration has no built in support for typed configs today though, so if you want to use that approach you have to implement the typed layer yourself (you can get pretty much help though by looking at the code for nJupiter.Abstraction.Logging, as you can see there it is not much code you have to add to achieve this).

**Comment by kalarani** [comment]
Thanks for the detailed response. Unfortunately, the application that i'm working on does not have a DI framework. And, I'm using the ```ConfigurationRepository.Instance``` directly to get hold of a ```IConfigRepository``` object. 

Is there a way, in which I get back a mock object from the Singleton?

**Comment by twilek** [comment]
Then I really suggest you to considering to start using an IoC container. Else you will have to use a dependency-breaking strategy (read more about that in the book Working Effectively with Legacy Code by Michael Feathers).

You can for example parameterize the constructor in this way (where the first constructor is used in production, and the second constructor is used in your tests): 

	public class MyClass {

		private readonly IConfigRepository configRepository;
		
		public MyClass() {
			this(ConfigurationRepository.Instance);
		}
	 
		public MyClass(IConfigRepository configRepository) {
			this.configRepository = configRepository;
		}

	}
	
Then you can simply inject the mock from your test exactly in the same way as the test in my previous post.

If you want to learn other ways to do this I suggest you read the book mentioned above.

**Comment by kalarani** [comment]
I fully understand the benefits of having an IoC container. But, in this case, i dont really have an option to use it. Moreover, the class that consumes the ```IConfigRepository``` is a static class and I can't have multiple constructors. I had to resort to using reflections to set the mock config repository for testing.

Thanks for the suggestion. That is definitely a worthy read.

**Comment by twilek** [comment]
If you ask me static classes shall in most cases be avoided at all costs, especially when writing testable code. If you still have one, use a static setter to set you mock (you can also read about this, and why this is better in the book I mention before), that is way better than reflection, testable code shall always go before encapsulation. The best thing would probably be to redactor your code though.
